import '@/styles/globals.css';
import type { Metadata } from 'next';
import Navbar from '@/components/Navbar';
import { Inter, Inconsolata, Roboto } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });
const inconsolata = Inconsolata({ subsets: ['latin'] });
const roboto = Roboto({ subsets: ['latin'], weight: ['400'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} antialiased`}>
        <Navbar />
        <main className='max-w-3xl mx-auto py-10'>
          {/* Inconsolata 폰트를 적용할 섹션 */}
          <section className={inconsolata.className}>
            <h1>Inconsolata 폰트로 렌더링되는 텍스트</h1>
          </section>

          {/* Roboto 폰트를 적용할 섹션 */}
          <section className={roboto.className}>
            <p>이 부분은 Roboto 폰트로 렌더링됩니다.</p>
          </section>
          {children}
        </main>
      </body>
    </html>
  );
}
